### ISSUE TITLE
Decouple feed from user

### ISSUE THREAD

**Issue by Neobii** [copleykj/socialize-postable#3]
It would be nice to be able to attach feeds to different things, like individual pages or groups.

**Comment by copleykj** [comment]
I like this idea. I think that the same pattern used in the likeable/commentable, combined with a factory pattern could be useful here. It would possibly look something like this.

``` javascript
//make User class postable. This will add a feed() method
//to the User class which returns a user scoped feed.
PostableModel.makePostable(User);

let usersFeed = Meteor.users.findOne().feed();

usersFeed.addPost("The quick brown fox.."); 

//same with a Group class
PostableModel.makePostable(Group);

let groupFeed = Meteor.groups.findOne().feed();

groupFeed.addPost("Jumps over the lazy dog!")
```

This is actually a good beginning to a bunch of work that I would like to complete to make groups and event listings. Would also need to create `requestable` and `invitable` packages which would allow requesting access to and inviting users to groups/events and would really polish off the package set :)

**Comment by Neobii** [comment]
I just simply added type onto post for now, like type = "user", type =
"group", type = "global" (just incase people want a feed that isn't
necessarily attached to another collection).

**Comment by copleykj** [comment]
Ok, so I have this worked out on a local branch. At this point I'm using the new (unreleased and updated for ES6) BaseModel API and the ES6 abstract class/mixin syntax and it looks like this:

``` javascript
class User extends PostableModel(BaseModel) {
    constructor(document){
        super(document)
    }

    awesomeHelperFunction() {
        return "Everything Is Awesome!"
    }
}

User.attachCollection(Meteor.users());

Meteor.user().feed().addPost("User adds a post to their own feed!");

Meteor.users.findOne({username:"copleykj"}).feed().addPost("User adds post to copleykj's feed");

let GroupsCollection = new Mongo.Collection("groups");

class Group extends PostableModel(BaseModel) {
    constructor(document) {
        super(document)
    }
}

Group.attachCollection(GroupsCollection);

GroupsCollection.findOne({name:"Socializers"}).feed().addPost("This is a post to a group");

```

This should satisfy the decoupling and give the freedom to create posts on any other model. Let me know what you think.

**Comment by Neobii** [comment]
I think it looks sufficiently decoupled.  However it doesn't seem as
composable to attach the collection to a predefined model rather than
decorating the collection with the models we create.

**Comment by copleykj** [comment]
Can you explain what you mean by it not being as composable?

**Comment by Neobii** [comment]
I think maybe the semantics of the syntax are confusing me a lil.  For example,

``` javascript
class User extends LikeableModel(BaseModel) {
    constructor(document){
        super(document)
    }

    awesomeHelperFunction() {
        return "Everything Is Awesome!"
    }
}
```

Would this mean that a user can like things?

**Comment by Neobii** [comment]
Also, there are a lot of similarities between the messages and the post collection.  It would be nice to be able to decorate a base message object somehow, because you might want some features like "readBy" on post or the ability to upload an image in the replace of anything that has a `body` property.  In another app I'm making, I have a mail package that has some subtle differences between the messages package.  I think with sufficient composability, we can make posts/ messages/ and my mail stuff all be built from the same components.

**Comment by copleykj** [comment]
Hmm, I really think this would be trying to mash two things together just because they sort of seem similar. The problem is that the messaging package is much more complex and I don't think would fit well together with general postings just because a message is a lot like a post.
