### ISSUE TITLE
Post body processing

### ISSUE THREAD

**Issue by Neobii** [copleykj/socialize-postable#4]
When someone posts a link, we should be able to do some parsing to find links and fetch meta data  with packages like: https://atmospherejs.com/konecty/autolinker and https://atmospherejs.com/acemtp/meta-extractor.

**Comment by copleykj** [comment]
You can currently accomplish this by using collection-hooks

**Comment by Neobii** [comment]
I'll think about this feature more, maybe this could be a separate
package.  It would be nice to also add @ and # to any kind of socialize
collection that has a text type field on it.

**Comment by StorytellerCZ** [comment]
@Neobii That would be a feature of the WYSIWYG editor you are using. You save either a string or an object, which allows you to use editors like Draft.js for this feature. Same with #5.
