### ISSUE TITLE
How To Delete Post From Feed()

### ISSUE THREAD

**Issue by ghost** [copleykj/socialize-postable#8]
I searched how to remove post from feed() but I could not.

Please tell me how to do this.

**Comment by copleykj** [comment]
Posts inherit from BaseModel so you can call the remove method on a post instance.

**Comment by ghost** [comment]
I have solved this problem using following code:
```

import { Post } from 'meteor/socialize:feed';

'post.remove'(postId) {
      
      Post.collection._collection.remove({body: {$regex: postId}});
      return true;

}
```
